// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.Data;

#nullable disable

namespace NZWalks.Migrations.NZWalksDb
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250727190543_Minor correction for the Images table")]
    partial class MinorcorrectionfortheImagestable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "AKL",
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Code = "WGN",
                            Name = "Wellington"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Code = "CAN",
                            Name = "Canterbury"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Code = "NSN",
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Code = "BOP",
                            Name = "Bay of Plenty"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Code = "WKO",
                            Name = "Waikato"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Code = "TAS",
                            Name = "Taranaki"
                        },
                        new
                        {
                            Id = new Guid("34343434-3434-3434-3434-343434343434"),
                            Code = "HKB",
                            Name = "Hawke's Bay"
                        },
                        new
                        {
                            Id = new Guid("56565656-5656-5656-5656-565656565656"),
                            Code = "MBH",
                            Name = "Marlborough"
                        },
                        new
                        {
                            Id = new Guid("78787878-7878-7878-7878-787878787878"),
                            Code = "OTG",
                            Name = "Otago"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Description = "Spectacular volcanic walk",
                            DifficultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LengthInKm = 19.399999999999999,
                            Name = "Tongariro Alpine Crossing",
                            RegionId = new Guid("12121212-1212-1212-1212-121212121212")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Description = "Coastal track with beaches",
                            DifficultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LengthInKm = 60.0,
                            Name = "Abel Tasman Coast Track",
                            RegionId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            Description = "Mountainous scenery",
                            DifficultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LengthInKm = 32.0,
                            Name = "Routeburn Track",
                            RegionId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            Description = "Coastal forest walk",
                            DifficultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LengthInKm = 70.0,
                            Name = "Queen Charlotte Track",
                            RegionId = new Guid("56565656-5656-5656-5656-565656565656")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            Description = "Great walk with lakes and forests",
                            DifficultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LengthInKm = 60.0,
                            Name = "Kepler Track",
                            RegionId = new Guid("78787878-7878-7878-7878-787878787878")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            Description = "Diverse landscapes",
                            DifficultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LengthInKm = 78.0,
                            Name = "Heaphy Track",
                            RegionId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            Description = "Short easy nature walk",
                            DifficultyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LengthInKm = 2.0,
                            Name = "Mount Bruce Walk",
                            RegionId = new Guid("34343434-3434-3434-3434-343434343434")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000008"),
                            Description = "Rainforest walk near Auckland",
                            DifficultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LengthInKm = 10.0,
                            Name = "Waitakere Ranges Track",
                            RegionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000009"),
                            Description = "Lakeside walk",
                            DifficultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LengthInKm = 46.0,
                            Name = "Lake Waikaremoana Great Walk",
                            RegionId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000010"),
                            Description = "Coastal and forest walk",
                            DifficultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LengthInKm = 55.0,
                            Name = "Paparoa Track",
                            RegionId = new Guid("78787878-7878-7878-7878-787878787878")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000011"),
                            Description = "Stewart Island walk",
                            DifficultyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LengthInKm = 32.0,
                            Name = "Rakiura Track",
                            RegionId = new Guid("78787878-7878-7878-7878-787878787878")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000012"),
                            Description = "Scenic coastal walk",
                            DifficultyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LengthInKm = 20.0,
                            Name = "Coromandel Coastal Walk",
                            RegionId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000013"),
                            Description = "Volcanic alpine circuit",
                            DifficultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LengthInKm = 35.0,
                            Name = "Pouakai Circuit",
                            RegionId = new Guid("12121212-1212-1212-1212-121212121212")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000014"),
                            Description = "Hilltop views",
                            DifficultyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LengthInKm = 5.0,
                            Name = "Queenstown Hill Walk",
                            RegionId = new Guid("78787878-7878-7878-7878-787878787878")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000015"),
                            Description = "Long-distance trail",
                            DifficultyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LengthInKm = 3000.0,
                            Name = "Te Araroa Trail",
                            RegionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.Models.Domain.Region", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Region", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
